### PR TITLE
fix: jsonapi specs according to 1.0 specifications

### PR DESCRIPTION
**Pull request by gottfrois**
I have not included `links`. Not sure whether you want to test with them or not.

### CODE REVIEW

**Comment by thegcat** [comment]
These are just formatting changes, correct? (I can't remember the spec mentioning formatting, so the question is curiosity, not criticism :-) )

**Comment by gottfrois** [comment]
the specs changed how array should be treated in "relationships"


Before

```
"musicians" => [
  { "data" => { "type" => "musicians", "id" => "1" } },
  { "data" => { "type" => "musicians", "id" => "2" } }
]
```

After

```
"musicians" => {
  "data" => [
    { "type" => "musicians", "id" => "1" },
    { "type" => "musicians", "id" => "2" }
  ]
}
```

**Comment by thegcat** [comment]
I missed that one indeed, thanks for the fix!

**Comment by apotonick** [comment]
Totally trusting @gottfrois here as I have no idea.

Can we add tests for `links`, too? Thanks you two, legends!

**Pull request merged**
