### PR TITLE
JSON API Uniq objects in "included"

### PR DESCRIPTION
**Pull request by thhermansen**
I'm not 100% sure if I found the best way of implementing the following:

1. Within the `included` part of JSON API we only want to include entities once.
2. When we do use `included` we only include type and id in `relationships`. The entities' attributes are found within the included data.

I do hope it looks acceptable :-)

### CODE REVIEW

**Comment by apotonick** [comment]
Is that another little quirk in the super fuzzy JSON API spec or is that an idea of yours?

PR looks good! :smile:

**Comment by thhermansen** [comment]
If I understand it correctly it is within the spec. Please see here [compound documents](http://jsonapi.org/format/#document-compound-documents) from the spec.

> A compound document MUST NOT include more than one resource object for each type and id pair.

It also seems to me that when in the examples when resource objects are included, they only have a reference in the `data.relationships`, which includes the `type` and `id`. The attributes for these records are found within the `included` part.

**Comment by apotonick** [comment]
Yeah, thanks, I re-read the specs (the 2461th time now) and I now understand the `relationships` section should not contain `data` or `attributes`, is that right?

Can you quickly jump into https://gitter.im/trailblazer/chat so we can have a brief chat? :beers:

**Comment by thhermansen** [comment]
I think that `relationships` should have `data`, but within `data` no `attributes` should be present. Only the `type` and `id`.

Example:

```json
{
  "data": [{
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "links": {
      "self": "http://example.com/articles/1"
    },
    "relationships": {
      "author": {
        "links": {
          "self": "http://example.com/articles/1/relationships/author",
          "related": "http://example.com/articles/1/author"
        },
        "data": { "type": "people", "id": "9" }
      },
      "comments": {
        "links": {
          "self": "http://example.com/articles/1/relationships/comments",
          "related": "http://example.com/articles/1/comments"
        },
        "data": [
          { "type": "comments", "id": "5" },
          { "type": "comments", "id": "12" }
        ]
      }
    }
```

**Comment by apotonick** [comment]
Is that what you meant? https://github.com/apotonick/roar/commit/fb21cb05b68af796d661a7245575038125bf88f0#diff-a6c482bcc8f1f9fedfd38aa4f00ec05cR28

**Comment by thhermansen** [comment]
@apotonick - Yes, that diff seems good.

What this pull request now offers, which I don't think you have in master(?) is removing duplicate objects within the `included` array, found [here](https://github.com/thhermansen/roar/blob/uniq-json-api-included/lib/roar/json/json_api.rb#L125-L129), and tests for it.

**Comment by apotonick** [comment]
Excellent work, @thhermansen, really! :heart: 

I just learned how to use `Set`!

**Pull request merged**
