### PR TITLE
Failing test for JSONAPI linked property

### PR DESCRIPTION
**Pull request by pd**
Using `compound { collection ... }`, which I _think_ is the right way to render associations into the `linked` property in a JSON API representation, does not roll them up into a single property; see http://jsonapi.org/format/#document-structure-compound-documents for the expected structure.

I tried to fix this one myself but haven't managed it yet. =)

### CODE REVIEW

**Comment by apotonick** [comment]
Thanks @pd for that test! I haven't had the time, yet, to look into it!

**Comment by pd** [comment]
Just a heads up on this note; JSON-API looks like it's about to be pretty significantly different: https://github.com/json-api/json-api/pull/341. So this might not be worth addressing; [linked](https://github.com/dgeb/json-api/blob/v1rc2/format/index.md#compound-documents-) could be much easier to implement in rc2.

It's a very open question for if/how roar should support both the current form of the spec and this newer version, assuming it stabilizes and actually hits 1.0.

**Comment by jillalynch** [comment]
@apotonick This would be really helpful in designing my API correctly.  Is there anything I can do to help resolve this?

**Comment by r1chardlee** [comment]
@apotonick Would be great to get this in, as we're working around the inability to include linked resources.

**Comment by apotonick** [comment]
Ok, I need your help. Someone has to summarise what has changed and what is wrong in the current tests. Also, please add tests where features are missing.

I don't use JSON-API and have no idea what needs to get fixed.

**Comment by apotonick** [comment]
Or... wait... is this attached test all that has to be changed for 1.0? :wolf:

**Comment by summera** [comment]
@apotonick 
How it is now with the current implementation:
```ruby
{
  "albums"=> {"id"=>1}, 
  "linked"=> {
    "songs"=> [
      {"songs"=>{"id"=>1, "title"=>"Stand Up"}}, 
      {"songs"=>{"id"=>2, "title"=>"Audition Mantra"}}
    ]
  }
}
```

How it should be:
```ruby
{
  'albums' => { 'id' => 1 },
  'linked' => {
    'songs' => [
      {'id' => 1, 'title' => 'Stand Up'},
      {'id' => 2, 'title' => 'Audition Mantra'}
    ]
  }
}
```

The current tests only cover `compound` with inline properties. Not `compound` referencing another Representer via `collection`.

**Comment by apotonick** [comment]
So the second wrap `songs` is redundant. Is that really all that's missing from the new spec?

Thanks @summera !

**Comment by summera** [comment]
No problem! :) Yep the second wrap songs is redundant. This is according to the older [JSON API compound document spec](https://github.com/json-api/json-api/blob/5fecffa48d2c4036ef5b4dbfdd4407d67b5e4560/format/index.md#compound-documents-) which the current version of Roar covers. 

You can see from the [current tests](https://github.com/pd/roar/blob/linked/test/json_api_test.rb#L136) that `compound` with inline properties render correctly. However using `collection` within `compound` adds the redundant wrap.

**Comment by summera** [comment]
@apotonick I've narrowed this problem down, but haven't quiet figured out a good way to fix it yet. Let me know if you have any suggestions. 

[`Roar::JSON::JSONAPI::Document#to_hash`](https://github.com/apotonick/roar/blob/master/lib/roar/json/json_api.rb#L113) calls [`#to_document`](https://github.com/apotonick/roar/blob/master/lib/roar/json/json_api.rb#L130) which wraps the document in `representable_attrs[:_wrap]`. This doesn't work when you have a `collection` declared that extends another Representer (like we do in this case), because it ends up wrapping each nested resource within the collection with  `representable_attrs[:_wrap]`. This gives us the redundant wrap, `songs`. 

If we were to return the resource without calling `#to_document` when we have a declared `collection` this test would pass. This is done in [some cases](https://github.com/apotonick/roar/blob/master/lib/roar/json/json_api.rb#L116), but not in this case.

**Pull request closed without merging**
